### PR TITLE
Async poll sync status

### PR DESCRIPTION
**Pull request by keroro520**

### CODE REVIEW

**Review by keroro520 — COMMENTED** [review]
#sync-mainnet

**Review by keroro520 — COMMENTED** [review]
#sync-mainnet

**Comment by keroro520** [comment]
This is a comment

**Comment by keroro520** [comment]
|

**Comment by keroro520** [comment]
`cat 1`

**Comment by keroro520** [comment]
a

**Comment by keroro520** [comment]
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0 (c978940 2021-09-13) | 6:29:23 | 239 | 5590384 | instance-ap-northeast-1 | ckb |
| 0.100.0 (c978940 2021-09-13) | 6:29:34 | 239 | 5590385 | instance-ap-southeast-1 | ckb |

**Comment by keroro520** [comment]
markdown_report

**Comment by keroro520** [comment]
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0 (c978940 2021-09-13) | 6:29:23 | 239 | 5590384 | instance-ap-northeast-1 | ckb |
| 0.100.0 (c978940 2021-09-13) | 6:29:34 | 239 | 5590385 | instance-ap-southeast-1 | ckb |

**Comment by keroro520** [comment]
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0 (c978940 2021-09-13) | 6:29:23 | 239 | 5590384 | instance-ap-northeast-1 | ckb |
| 0.100.0 (c978940 2021-09-13) | 6:29:34 | 239 | 5590385 | instance-ap-southeast-1 | ckb |

**Comment by keroro520** [comment]
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0 (c978940 2021-09-13) | 6:29:23 | 239 | 5590384 | instance-ap-northeast-1 | ckb |
| 0.100.0 (c978940 2021-09-13) | 6:29:34 | 239 | 5590385 | instance-ap-southeast-1 | ckb |

**Comment by keroro520** [comment]
Sync-Mainnet crashed

**Comment by keroro520** [comment]
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0-pre (ef31ace 2021-10-12) | 6:23:59 | 242 | 5595243 | instance-ap-northeast-1 | ckb |
| 0.100.0-pre (ef31ace 2021-10-12) | 6:24:00 | 242 | 5595243 | instance-ap-southeast-1 | ckb |
| 0.100.0-pre (ef31ace 2021-10-12) | 6:24:01 | 242 | 5595243 | instance-us-east-1 | ckb |
| 0.100.0-pre (ef31ace 2021-10-12) | 6:24:02 | 242 | 5595243 | instance-us-west-1 | ckb |

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report
Sync-Mainnet crashed

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report:**
Sync-Mainnet crashed

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report:**
Sync-Mainnet crashed

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report:**
Sync-Mainnet crashed

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report
Sync-Mainnet crashed

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report**:
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0-pre (64b0d97 2021-10-15) | 0:01:26 | 0 | 10 | instance-ap-northeast-1 | ckb |
| 0.100.0-pre (64b0d97 2021-10-15) | 0:01:21 | 0 | 10 | instance-ap-southeast-1 | ckb |
| 0.100.0-pre (64b0d97 2021-10-15) | 0:01:34 | 0 | 10 | instance-us-west-1 | ckb |

**Comment by nervos-bot-user** [comment]
**Sync-Mainnet Report**:
| Version | Time(s) | Speed | Tip | Hostname | Network |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 0.100.0-pre (64b0d97 2021-10-15) | 5:40:09 | 275 | 5621472 | instance-ap-northeast-1 | ckb |
| 0.100.0-pre (64b0d97 2021-10-15) | 5:33:21 | 281 | 5621472 | instance-ap-southeast-1 | ckb |
| 0.100.0-pre (64b0d97 2021-10-15) | 6:03:43 | 257 | 5621472 | instance-us-west-1 | ckb |

**Comment by keroro520** [comment]
hello

**Comment by nervos-bot-user** [comment]
hello

**Comment by nervos-bot-user** [comment]
hello

**Pull request closed without merging**
